pragma Singleton
import QtQuick

QtObject {
    readonly property var sources: [
        [
            "images/f1.png",
            "images/f2.png",
            "images/f3.png",
            "images/f4.png",
            "images/fc1.png",
            "images/fc2.png",
            "images/fc3.png",
            "images/fc4.png",
        ],
        [
            "images/r1.png",
            "images/r2.png",
            "images/r3.png",
            "images/r4.png",
            "images/rc1.png",
            "images/rc2.png",
            "images/rc3.png",
            "images/rc4.png",
        ],
        [
            "images/s1.png",
            "images/s2.png",
            "images/s3.png",
            "images/s4.png",
            "images/sc1.png",
            "images/sc2.png",
            "images/sc3.png",
            "images/sc4.png",
        ],
        [
            "images/k1.png",
            "images/k2.png",
            "images/k3.png",
            "images/k4.png",
            "images/kc1.png",
            "images/kc2.png",
            "images/kc3.png",
            "images/kc4.png",
        ],
        [
            "images/m1.png",
            "images/m2.png",
            "images/m3.png",
            "images/m4.png",
            "images/mc1.png",
            "images/mc2.png",
            "images/mc3.png",
            "images/mc4.png",
        ],
        [
            "images/h1.png",
            "images/h2.png",
            "images/h3.png",
            "images/h4.png",
            "images/hc1.png",
            "images/hc2.png",
            "images/hc3.png",
            "images/hc4.png",
        ],
        [
            "images/p1.png",
            "images/p2.png",
            "images/p3.png",
            "images/p4.png",
            "images/pc1.png",
            "images/pc2.png",
            "images/pc3.png",
            "images/pc4.png",
        ]
    ]
}
